### ISSUE TITLE
It doesnt work

### ISSUE THREAD

**Issue by newbialywhodis** [Waffle408/esx_mdt#1]
No commands, it wont even open, no errors aswell

**Comment by Waffle408** [comment]
Do /mdt, But make sure your a police officer first.

**Comment by newbialywhodis** [comment]
Im sure that im officer (my jobs show me as captain)

**Comment by Waffle408** [comment]
I've just pushed an edit, It was originally for an older version of ESX I've updated it now.

**Comment by newbialywhodis** [comment]
![image](https://user-images.githubusercontent.com/118001434/202178873-1d273eff-60b3-430c-9ed2-208511585248.png)
now i can type /mdt, but getting this error, Do i have to swap xPlayer?

**Comment by Waffle408** [comment]
Sorry for the late reply, It should 100% work now, If you download the latest PR

**Comment by newbialywhodis** [comment]
Downloaded latest, I can now open mdt - But cannot search persons, cannot hide tablet (even with logout button), and ye. Something still wrong ;/

**Comment by newbialywhodis** [comment]
(no errors)

**Comment by Waffle408** [comment]
DId you run the SQL?

**Comment by newbialywhodis** [comment]
Yes i do, u sure its really for esx legacy?

**Comment by newbialywhodis** [comment]
Now i did whole mdt reinstall, database etc. Still i cant turn off mdt, search someone in db etc

**Comment by Waffle408** [comment]
Rename the script to "esx-mdt" should fix it.

And yes it's for esx legacy, just an older version but yea it should work now,I'll make a proper PR tomorrow to fix it.
